services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: weloveplants
      MYSQL_DATABASE: mydb
    ports:
      - 3307:3306
    volumes:
      - my-db-volume:/var/lib/mysql

volumes:
  my-db-volume: